<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alloy Plan</name>
   <tag></tag>
   <elementGuidId>54ff14bc-9b53-428d-88ab-ab920c4fb404</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/alloy-plan/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alloy Plan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;span10&quot;]/div[@class=&quot;alloyMenu&quot;]/div[@class=&quot;navbar&quot;]/div[@class=&quot;navbar-inner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;nav-collapse&quot;]/ul[@class=&quot;nav&quot;]/li[2]/a[@class=&quot;theme3&quot;]</value>
   </webElementProperties>
</WebElementEntity>
